name: Feature Branch Build
run-name: Feature Branch Build

on:
  pull_request:
    branches:
      - main

jobs:
  feature_branch:
    name: Feature Branch Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: dotnet tool update -g docfx

      - run: docfx docs/docfx.json --output docs/_site
