name: Main Branch Build
run-name: Main Branch Build

on:
  push:
    branches:
      - main

jobs:
  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - run: dotnet tool update -g docfx

      - run: docfx docs/docfx.json --output docs/_site

      - name: Setup pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
          publish_dir: docs/_site
