name: Main Branch Build
run-name: Main Branch Build

on:
  push:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}

  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    needs: debug
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - run: dotnet tool update -g docfx

      - run: docfx docs/docfx.json --output docs/_site

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
        with:
          path: "docs/_site"

      - name: Deploy to Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
        id: deployment
        uses: actions/deploy-pages@v4

